Tx 7
osadolortech/tweet_clonev2 pull request #9
Opened 2022-07-11 15:29 UTC by osadolortech

2022-07-11 15:45 UTC, iamr0b0tx requested changes

2022-07-11 15:45 UTC, iamr0b0tx commented on tweetapi/models.py
> +    content = models.TextField(max_length=160,blank=True,null=True)
why null?

2022-07-11 15:45 UTC, iamr0b0tx commented on tweetapi/registration.py
> +            raise serializers.ValidationError({"password": "password filed didnt match"})
spelling

2022-07-11 15:58 UTC, osadolortech commented on tweetapi/models.py
> +    content = models.TextField(max_length=160,blank=True,null=True)
fixed

2022-07-11 15:58 UTC, osadolortech commented on tweetapi/registration.py
> +            raise serializers.ValidationError({"password": "password filed didnt match"})
fixed

2022-07-11 20:57 UTC, merged

2022-10-11 08:53 UTC, osadolortech commented
The null=True was a mistake, I had a case where I was testing the API and I
forgot to remove it.

On Mon, 11 Jul 2022 at 16:45, Christian ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In tweetapi/models.py
> <https://github.com/osadolortech/tweet_clonev2/pull/9#discussion_r918087446>
> :
>
> > @@ -14,7 +14,7 @@ class ProfileModel(models.Model):
>
>  class TweetModel(models.Model):
>      owner = models.ForeignKey(User,on_delete=models.CASCADE, related_name='tweet')
> -    content = models.TextField(max_length=160,blank=True)
> +    content = models.TextField(max_length=160,blank=True,null=True)
>
> why null?
> ------------------------------
>
> In tweetapi/registration.py
> <https://github.com/osadolortech/tweet_clonev2/pull/9#discussion_r918088182>
> :
>
> > +from rest_framework.validators import UniqueValidator
> +
> +
> +class RegistrationSerializer(serializers.ModelSerializer):
> +    email = serializers.EmailField(required=True, validators=[UniqueValidator(queryset=User.objects.all())])
> +    password = serializers.CharField(required=True,write_only=True, validators=[validate_password])
> +    password_confirmation = serializers.CharField(required=True,write_only=True)
> +    class Meta:
> +        model= User
> +        fields=(
> +            "first_name","last_name","username","email","password","password_confirmation"
> +        )
> +        extra_kwargs= {"first_name":{'required':True}, "last_name":{'required':True}}
> +    def validate(self, attrs):
> +        if attrs["password"] != attrs["password_confirmation"]:
> +            raise serializers.ValidationError({"password": "password filed didnt match"})
>
> spelling
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/osadolortech/tweet_clonev2/pull/9#pullrequestreview-1034560174>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVWPQP5UUPGBMZDGULWF5ALVTQ6R7ANCNFSM53H5QPTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>